platform :ios, '10.0'

target 'Homework_API' do
  use_frameworks!

 pod 'ObjectMapper', '~> 2.2'
 pod 'Kingfisher', '~> 3.0'
 pod 'FontAwesome.swift'
 pod 'Cosmos', '~> 7.0'
 pod 'PKHUD', '~> 4.0'
 pod 'DKImagePickerController'
 pod 'Alamofire', '~> 4.0'
end
